# Test setup — source all pipeline modules

# Define %||% operator (null-coalescing, not in base R)
`%||%` <- function(a, b) if (!is.null(a)) a else b

# Resolve pipeline root: test_path() returns the test directory path;
# going up two levels from there gives the project root.
pipeline_dir <- normalizePath(file.path(
  dirname(testthat::test_path()), "..", ".."
), mustWork = TRUE)

# Source in dependency order
source(file.path(pipeline_dir, "R", "constants.R"))
source(file.path(pipeline_dir, "R", "utils.R"))
source(file.path(pipeline_dir, "R", "00_config.R"))
source(file.path(pipeline_dir, "R", "01_gene_input.R"))
source(file.path(pipeline_dir, "R", "02_enzyme_site_scan.R"))
source(file.path(pipeline_dir, "R", "03_codon_table.R"))
source(file.path(pipeline_dir, "R", "04_mutation_design.R"))
source(file.path(pipeline_dir, "R", "05_tiling.R"))
source(file.path(pipeline_dir, "R", "06_overhang_selection.R"))
source(file.path(pipeline_dir, "R", "07_barcode_design.R"))
source(file.path(pipeline_dir, "R", "08_oligo_assembly.R"))
source(file.path(pipeline_dir, "R", "09_wt_geneblock_design.R"))
source(file.path(pipeline_dir, "R", "10_qc_checks.R"))
source(file.path(pipeline_dir, "R", "11_output.R"))

# --- Test fixtures ---
# A short synthetic test gene (100 codons = 300 nt)
# Starts ATG, ends with stop (TAA), no internal stops
# Contains one embedded BsmBI site (CGTCTC) at position 91-96 for testing domestication

# Build a clean 300 nt test gene
TEST_GENE_SEQ <- paste0(
  # 100 codons = 300 nt, starts ATG, ends TAA
  "ATG", "GCT", "GAA", "CTT", "AAA", "GCT", "GCC", "AAG", "GAT", "TTC",  # 1-10
  "GGT", "ACC", "CTG", "AAC", "GAT", "ATC", "CCA", "GCT", "CAG", "AAG",  # 11-20
  "TTC", "ATC", "GCT", "AAC", "CTG", "TGG", "AAG", "AAC", "GGT", "GAC",  # 21-30
  "TTC", "CGT", "CTC", "GAT", "CTG", "AAA", "GAA", "CTG", "GCT", "GAC",  # 31-40 (CGTCTC at codons 32-33)
  "TAC", "ATC", "AAG", "AAC", "CCG", "GCT", "ACC", "GTT", "GCT", "CTG",  # 41-50
  "GAA", "GGT", "ATC", "GCT", "AAC", "GGT", "GCT", "CCG", "ATC", "TTC",  # 51-60
  "AAA", "GCT", "GCT", "AAA", "GAA", "CTG", "ATC", "GAA", "TCC", "TTC",  # 61-70
  "GCT", "TAC", "GTT", "AAA", "GCT", "ACC", "AAA", "GGT", "GAA", "AAC",  # 71-80
  "CTG", "ATC", "TCC", "GCT", "ATC", "GAC", "AAA", "GCT", "GTT", "GAC",  # 81-90
  "AAA", "CTG", "GCT", "GAA", "TAC", "ATC", "AAA", "GCT", "GAA", "TAA"   # 91-100 (100th = stop)
)

TEST_POLIII <- "GAGGGCCTATTTCCCATGATTCCTTCATATTTGCATATACGATACAAGGCTGTTAGAGAGATAATTAGAATTAATTTGACTGTAAACACAAAGATATTAGTACAAAATACGTGACGTAGAAAGTAATAATTTCTTGGGTAGTTTGCAGTTTTAAAATTATGTTTTAAAATGGACTATCATATGCTTACCGTAACTTGAAAGTATTTCGATTTCTTGGCTTTATATATCTTGTGGAAAGGACGAAACACCG"

# A longer synthetic test gene (700 codons = 2100 nt) for superblock testing.
# Constructed from a repeating 40-codon pattern that is free of BsaI/BsmBI/PaqCI
# sites on both strands. At 2100 nt + 250 nt PolIII + 22 overhead = 2372 > 1800,
# this gene triggers superblock boundary placement.
TEST_LONG_GENE_SEQ <- paste0(
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "ATGGCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTC",
  "ATCGCTAACCTGTGGAAGAACGCTGACTACATCAAGAACCCGGCTACCGTTGCTCTGGAA",
  "GCTGAACTTAAAGCTGCCAAGGATTTCACCCTGAACGATATCCCAGCTCAGAAGTTCTAA"
)

# TRIO gene (NM_007118.4) — 9294 nt (3098 codons), starts ATG, ends TGA
# Contains 20 enzyme sites: 8 BsaI (2 fwd + 6 RC), 8 BsmBI (3 fwd + 5 RC), 4 PaqCI (1 fwd + 3 RC)
# Used for stress-testing superblocking, extensive domestication, and large barcode pools
TEST_TRIO_SEQ <- paste0(
  "ATGAGCGGCAGCAGCGGCGGAGCCGCCGCCCCCGCCGCGTCCTCCGGCCCCGCCGCGGCG",
  "GCCAGCGCGGCTGGCTCGGGCTGCGGGGGCGGTGCCGGCGAGGGGGCAGAGGAGGCGGCC",
  "AAGGACCTGGCCGACATCGCGGCCTTCTTCCGATCCGGGTTTCGAAAAAACGATGAAATG",
  "AAAGCTATGGATGTTTTACCAATTTTGAAGGAAAAAGTTGCATACCTTTCAGGTGGGAGA",
  "GATAAACGTGGAGGTCCCATTTTAACGTTTCCGGCCCGCAGCAATCATGACAGAATACGA",
  "CAGGAGGATCTCAGGAGACTCATTTCCTATCTAGCCTGTATTCCCAGCGAGGAGGTCTGC",
  "AAGCGTGGCTTCACGGTGATCGTGGACATGCGTGGGTCCAAGTGGGACTCCATCAAGCCC",
  "CTTCTGAAGATCCTGCAGGAGTCCTTCCCCTGCTGCATCCATGTGGCCCTGATCATCAAG",
  "CCAGACAACTTCTGGCAGAAACAGAGGACTAATTTTGGCAGTTCTAAATTTGAATTTGAG",
  "ACAAATATGGTCTCTTTAGAAGGCCTTACCAAAGTAGTTGATCCTTCTCAGCTAACTCCT",
  "GAGTTTGATGGCTGCCTGGAATACAACCACGAAGAATGGATTGAAATCAGAGTTGCTTTT",
  "GAAGACTACATTAGCAATGCCACCCACATGCTGTCTCGGCTGGAGGAACTTCAGGACATC",
  "CTAGCTAAGAAGGAGCTGCCTCAGGATTTAGAGGGGGCTCGGAATATGATCGAGGAACAT",
  "TCTCAGCTGAAGAAGAAGGTGATTAAGGCCCCCATCGAGGACCTGGATTTGGAGGGACAG",
  "AAGCTGCTTCAGAGGATACAGAGCAGTGAAAGCTTTCCCAAAAAGAACTCAGGCTCAGGC",
  "AATGCGGACCTGCAGAACCTCTTGCCCAAGGTGTCCACCATGCTGGACCGGCTGCACTCG",
  "ACACGGCAGCATCTGCACCAGATGTGGCATGTGAGGAAGCTGAAGCTGGACCAGTGCTTC",
  "CAGCTGAGGCTGTTTGAACAGGATGCTGAGAAGATGTTTGACTGGATCACACACAACAAA",
  "GGCCTGTTTCTAAACAGCTACACAGAGATTGGGACCAGCCACCCTCATGCCATGGAGCTT",
  "CAGACGCAGCACAATCACTTTGCCATGAACTGTATGAACGTGTATGTAAATATAAACCGC",
  "ATCATGTCGGTGGCCAATCGTCTGGTGGAGTCTGGCCACTATGCCTCGCAGCAGATCAGG",
  "CAGATCGCGAGTCAGCTGGAGCAGGAGTGGAAGGCGTTTGCGGCAGCCCTGGATGAGCGG",
  "AGCACCTTGCTGGACATGTCCTCCATTTTCCACCAGAAGGCCGAAAAGTATATGAGCAAC",
  "GTGGATTCATGGTGTAAAGCTTGCGGTGAGGTAGACCTTCCCTCAGAGCTGCAGGACCTA",
  "GAAGATGCCATTCATCACCACCAGGGAATATATGAACATATCACTCTTGCTTATTCTGAG",
  "GTCAGCCAAGATGGGAAGTCGCTCCTTGACAAGCTCCAGCGGCCCTTGACTCCCGGCAGC",
  "TCCGATTCCCTGACAGCCTCTGCCAACTACTCCAAGGCCGTGCACCATGTCCTGGATGTC",
  "ATCCACGAGGTGCTGCACCACCAGCGGCAGCTGGAGAACATCTGGCAACACCGCAAGGTC",
  "CGGCTGCATCAGAGGCTGCAGCTGTGTGTTTTCCAGCAGGACGTTCAGCAGGTGCTAGAC",
  "TGGATCGAGAACCACGGAGAAGCATTTCTGAGCAAACATACAGGTGTGGGGAAATCTCTT",
  "CATCGGGCCAGAGCATTGCAGAAACGTCATGAAGATTTTGAAGAAGTGGCACAGAACACA",
  "TACACCAATGCGGATAAATTACTGGAAGCAGCAGAACAGCTGGCTCAGACTGGGGAATGT",
  "GACCCCGAAGAGATTTATCAGGCTGCCCATCAGCTGGAAGACCGGATTCAAGATTTCGTT",
  "CGGCGTGTTGAGCAGCGAAAGATCCTACTGGACATGTCAGTGTCCTTTCACACCCATGTG",
  "AAAGAGCTGTGGACGTGGCTGGAGGAGCTGCAGAAGGAGCTGCTGGACGACGTGTATGCC",
  "GAGTCGGTGGAGGCCGTGCAGGACCTCATCAAGCGCTTTGGCCAGCAGCAGCAGACCACC",
  "CTGCAGGTGACTGTCAACGTGATCAAGGAAGGGGAGGACCTCATCCAGCAGCTCAGGGAC",
  "TCTGCCATCTCCAGTAACAAGACCCCCCACAACAGCTCCATCAACCACATTGAGACGGTG",
  "CTGCAGCAGCTGGACGAGGCGCAGTCGCAGATGGAGGAGCTCTTCCAGGAGCGCAAGATC",
  "AAGCTGGAGCTCTTCCTGCAGCTGCGCATCTTCGAGAGGGACGCCATCGACATTATCTCA",
  "GACCTCGAGTCTTGGAATGATGAGCTTTCTCAGCAAATGAATGACTTCGACACAGAAGAT",
  "CTCACGATTGCAGAGCAGCGCCTCCAGCACCATGCAGACAAAGCCTTGACCATGAACAAC",
  "TTGACTTTTGACGTCATCCACCAAGGGCAAGATCTTCTGCAGTATGTCAATGAGGTCCAG",
  "GCCTCTGGTGTGGAGCTGCTGTGTGATAGAGATGTAGACATGGCAACTCGGGTCCAGGAC",
  "CTGCTGGAGTTTCTTCATGAAAAACAGCAGGAATTGGATTTAGCCGCAGAGCAGCATCGG",
  "AAACACCTGGAGCAGTGCGTGCAGCTGCGCCACCTGCAGGCAGAAGTGAAACAGGTGCTG",
  "GGTTGGATCCGCAACGGAGAGTCCATGTTAAATGCCGGACTTATCACAGCCAGCTCGTTA",
  "CAAGAGGCAGAGCAGCTCCAGCGAGAGCACGAGCAGTTCCAGCATGCCATTGAGAAAACA",
  "CATCAGAGCGCGCTGCAGGTGCAGCAGAAGGCAGAAGCCATGCTACAGGCCAACCACTAC",
  "GACATGGACATGATCCGGGACTGCGCCGAGAAGGTGGCGTCTCACTGGCAACAGCTCATG",
  "CTCAAGATGGAAGATCGCCTCAAGCTCGTCAACGCCTCTGTCGCTTTCTACAAAACCTCA",
  "GAGCAGGTCTGCAGCGTCCTCGAGAGCCTGGAACAGGAGTACAAGAGAGAAGAAGACTGG",
  "TGTGGCGGGGCGGATAAGCTGGGCCCAAACTCTGAGACGGACCACGTGACGCCCATGATC",
  "AGCAAGCACCTGGAGCAGAAGGAGGCATTCCTGAAGGCTTGCACCCTTGCTCGGAGGAAT",
  "GCAGACGTCTTCCTGAAATACCTGCACAGGAACAGCGTGAACATGCCAGGAATGGTGACG",
  "CACATCAAAGCTCCTGAACAGCAAGTGAAAAATATCTTGAATGAACTCTTCCAACGGGAG",
  "AACAGGGTATTGCATTACTGGACCATGAGGAAGAGACGGCTGGACCAGTGTCAGCAGTAC",
  "GTGGTCTTTGAGAGGAGTGCCAAGCAGGCTTTGGAATGGATCCATGACAATGGCGAGTTC",
  "TACCTTTCCACACACACCTCCACGGGCTCCAGTATACAGCACACCCAGGAGCTCCTGAAA",
  "GAGCACGAGGAGTTCCAGATAACTGCAAAGCAAACCAAAGAGAGAGTGAAGCTATTGATA",
  "CAGCTGGCTGATGGCTTTTGTGAAAAAGGGCATGCCCATGCGGCAGAGATAAAAAAATGT",
  "GTTACTGCTGTGGATAAGAGGTACAGAGATTTCTCTCTGCGGATGGAGAAGTACAGGACC",
  "TCTTTGGAAAAAGCCCTGGGGATTTCTTCAGATTCCAACAAATCGAGTAAAAGTCTCCAG",
  "CTAGATATCATTCCAGCCAGTATCCCTGGCTCAGAGGTGAAACTTCGAGATGCTGCTCAT",
  "GAACTTAATGAAGAGAAGCGGAAATCTGCCCGCAGGAAAGAGTTCATAATGGCTGAGCTC",
  "ATTCAAACTGAAAAGGCTTATGTAAGAGACCTCCGGGAATGTATGGATACGTACCTGTGG",
  "GAAATGACCAGTGGCGTGGAAGAGATTCCACCTGGCATTGTAAACAAAGAACTCATCATC",
  "TTCGGAAACATGCAAGAAATCTACGAATTTCATAATAACATATTCCTAAAGGAGCTGGAA",
  "AAATATGAACAGTTGCCAGAGGATGTTGGACATTGTTTTGTTACTTGGGCAGACAAGTTT",
  "CAGATGTATGTCACATATTGCAAAAATAAGCCTGATTCTACTCAGCTGATATTGGAACAT",
  "GCAGGGTCCTATTTTGACGAGATACAGCAGCGACATGGATTAGCCAATTCCATTTCTTCC",
  "TACCTTATTAAACCAGTTCAGCGAATAACGAAGTATCAGCTCCTTTTAAAAGAGCTGCTG",
  "ACGTGCTGTGAGGAAGGAAAGGGAGAGATTAAAGATGGCCTGGAGGTGATGCTCAGCGTG",
  "CCGAAGCGAGCCAATGATGCCATGCACCTCAGCATGCTGGAAGGGTTTGATGAAAACATT",
  "GAGTCTCAGGGAGAACTCATCCTACAGGAATCCTTCCAAGTGTGGGACCCAAAAACCTTA",
  "ATTCGAAAGGGTCGAGAACGGCATCTCTTCCTTTTTGAAATGTCCTTAGTATTTAGTAAA",
  "GAAGTGAAAGATTCCAGTGGGAGAAGCAAGTACCTTTATAAAAGCAAATTGTTTACCTCA",
  "GAGTTGGGTGTCACAGAACATGTTGAAGGAGACCCTTGCAAATTTGCACTGTGGGTGGGG",
  "AGAACACCAACTTCAGATAATAAAATTGTCCTTAAGGCTTCCAGCATAGAGAACAAGCAG",
  "GACTGGATAAAGCATATCCGCGAAGTCATCCAGGAGCGGACGATCCACCTGAAGGGAGCC",
  "CTGAAGGAGCCCATTCACATCCCTAAGACCGCTCCCGCCACAAGACAGAAGGGAAGGAGG",
  "GATGGAGAGGATCTGGACAGCCAAGGAGACGGCAGCAGCCAGCCTGATACGATTTCCATC",
  "GCCTCACGGACGTCTCAGAACACGCTGGACAGCGATAAGCTCTCTGGTGGCTGTGAGCTG",
  "ACAGTGGTGATCCATGACTTCACCGCTTGCAACAGCAACGAGCTGACCATCCGACGGGGC",
  "CAGACCGTGGAAGTTCTGGAGCGGCCGCATGACAAGCCTGACTGGTGTCTGGTGCGGACA",
  "ACTGACCGCTCCCCAGCGGCAGAAGGCCTGGTCCCCTGTGGTTCACTGTGCATCGCCCAC",
  "TCCAGAAGTAGCATGGAAATGGAGGGCATCTTCAACCACAAAGACTCGCTCTCCGTCTCC",
  "AGCAATGACGCCAGTCCACCCGCATCCGTGGCTTCCCTCCAGCCCCACATGATCGGGGCC",
  "CAGAGCTCGCCGGGCCCCAAGCGGCCGGGCAACACCCTGCGCAAGTGGCTCACCAGCCCC",
  "GTGCGGCGGCTCAGCAGCGGCAAGGCCGACGGGCACGTGAAGAAGCTGGCGCACAAGCAC",
  "AAGAAGAGCCGCGAGGTCCGCAAGAGCGCCGACGCCGGCTCGCAGAAGGACTCCGACGAC",
  "AGTGCGGCCACCCCGCAGGACGAGACGGTCGAGGAGAGAGGCCGGAACGAGGGCCTGAGC",
  "AGCGGTACTCTCTCCAAATCCTCCTCCTCGGGGATGCAGAGCTGTGGAGAAGAGGAAGGC",
  "GAGGAGGGGGCCGACGCCGTGCCCCTGCCGCCACCCATGGCCATCCAGCAGCACAGCCTC",
  "CTCCAGCCAGACTCACAGGATGACAAGGCCTCTTCTCGGTTATTAGTCCGCCCCACCAGC",
  "TCCGAAACACCGAGTGCAGCCGAGCTCGTCAGTGCAATTGAGGAACTCGTGAAAAGCAAG",
  "ATGGCACTGGAGGATCGCCCCAGCTCACTCCTTGTTGACCAGGGAGATAGTAGCAGCCCT",
  "TCCTTCAACCCTTCGGATAATTCCCTTCTCTCTTCCTCCTCGCCCATTGATGAGATGGAA",
  "GAAAGGAAATCCAGCTCTTTAAAGAGAAGACACTACGTTTTGCAAGAACTAGTGGAGACA",
  "GAGCGTGACTATGTGCGGGACCTTGGCTATGTGGTTGAGGGCTACATGGCACTTATGAAA",
  "GAAGATGGTGTTCCTGATGACATGAAAGGAAAAGACAAAATTGTGTTCGGCAACATCCAT",
  "CAGATTTACGACTGGCACAGAGACTTTTTTTTAGGAGAGTTAGAGAAGTGCCTTGAAGAT",
  "CCAGAAAAACTAGGATCCCTTTTTGTTAAACACGAGAGAAGGTTGCACATGTACATAGCT",
  "TATTGTCAAAATAAACCAAAGTCTGAGCACATTGTCTCAGAATACATTGATACCTTTTTT",
  "GAGGACTTAAAGCAGCGTCTTGGCCACAGGTTACAGCTCACAGATCTGTTGATCAAACCA",
  "GTGCAGAGAATCATGAAGTATCAGCTGTTACTGAAGGACTTCCTCAAGTATTCCAAAAAG",
  "GCCAGCCTGGATACATCAGAATTAGAGAGAGCTGTGGAAGTCATGTGCATAGTACCCAGG",
  "CGGTGCAACGACATGATGAACGTGGGGCGGCTGCAAGGATTCGACGGGAAAATCGTTGCC",
  "CAGGGTAAACTGCTCTTGCAGGACACATTCTTGGTCACAGACCAAGATGCAGGACTTCTG",
  "CCTCGCTGCAGAGAGAGGCGCATCTTCCTCTTTGAGCAGATCGTCATATTCAGCGAACCA",
  "CTTGATAAAAAGAAGGGCTTCTCCATGCCGGGATTCCTGTTTAAGAACAGTATCAAGGTG",
  "AGTTGCCTTTGCCTGGAGGAAAATGTGGAAAATGATCCCTGTAAATTTGCTCTGACATCG",
  "AGGACGGGTGACGTGGTAGAGACCTTCATTTTGCATTCATCTAGTCCAAGTGTCCGGCAA",
  "ACTTGGATCCATGAAATCAACCAAATTTTAGAAAACCAGCGCAATTTTTTAAATGCCTTG",
  "ACATCGCCAATCGAGTACCAGAGGAACCACAGCGGGGGCGGCGGCGGCGGCGGCAGCGGG",
  "GGCAGCGGCGGGGGTGGGGGCAGCGGCGGCGGCGGGGCCCCCAGTGGCGGCAGCGGCCAC",
  "AGTGGCGGCCCCAGCAGCTGCGGCGGCGCCCCCAGCACGAGCAGGAGCCGGCCCTCCCGG",
  "ATCCCCCAGCCTGTCCGACACCACCCCCCCGTGCTGGTCTCCTCTGCAGCCTCGAGCCAG",
  "GCAGAGGCAGACAAGATGTCAGGTACGTCCACCCCCGGGCCCTCCCTGCCTCCCCCTGGC",
  "GCGGCCCCCGAGGCCGGCCCCAGCGCGCCCAGCAGGCGGCCCCCCGGCGCGGACGCCGAG",
  "GGGTCCGAGCGAGAAGCGGAGCCGATCCCCAAGATGAAGGTGCTGGAGAGCCCCAGGAAA",
  "GGCGCCGCGAACGCCTCGGGGTCGAGCCCAGACGCCCCCGCCAAGGACGCGCGCGCTAGC",
  "CTGGGCACCCTGCCGCTTGGGAAGCCCCGGGCCGGGGCCGCTTCGCCGCTGAACTCGCCG",
  "CTCTCCAGCGCGGTCCCTTCTCTCGGCAAGGAGCCCTTCCCCCCCAGCAGCCCCCTGCAG",
  "AAGGGGGGCTCCTTCTGGAGCTCCATCCCCGCCTCCCCCGCCAGCCGACCCGGCTCCTTC",
  "ACCTTCCCGGGGGACAGCGACTCCCTCCAGCGGCAGACACCCCGCCACGCGGCCCCTGGC",
  "AAGGATACTGACCGCATGAGCACGTGCTCCTCGGCCAGCGAGCAGTCCGTGCAGTCCACC",
  "CAGAGCAACGGGAGTGAAAGCAGCAGCAGTAGCAACATCTCCACCATGTTGGTGACACAC",
  "GATTACACGGCAGTGAAGGAGGATGAGATCAACGTCTACCAAGGAGAGGTCGTTCAAATT",
  "CTGGCCAGCAACCAGCAGAACATGTTTCTGGTGTTCCGAGCCGCCACTGACCAGTGCCCC",
  "GCAGCTGAGGGCTGGATTCCAGGCTTTGTCCTGGGCCACACCAGTGCAGTCATCGTGGAG",
  "AACCCGGACGGGACTCTCAAGAAGTCAACATCTTGGCACACAGCACTCCGTTTAAGGAAA",
  "AAATCTGAGAAAAAAGATAAAGACGGCAAAAGGGAAGGCAAGTTAGAGAACGGTTATCGG",
  "AAGTCACGGGAAGGACTCAGCAACAAGGTATCTGTGAAGCTTCTCAATCCCAACTACATT",
  "TATGACGTTCCCCCAGAATTCGTCATTCCATTGAGTGAGGTCACGTGTGAGACAGGGGAG",
  "ACCGTTGTTCTTAGATGTCGAGTCTGTGGCCGCCCCAAAGCCTCAATTACCTGGAAGGGC",
  "CCTGAACACAACACCTTGAACAACGATGGTCACTACAGCATCTCCTACAGTGACCTGGGA",
  "GAGGCCACGCTGAAGATTGTGGGCGTGACCACGGAAGATGACGGCATCTACACGTGCATC",
  "GCTGTCAATGACATGGGTTCAGCCTCATCGTCGGCCAGCCTGAGGGTCCTAGGTCCAGGG",
  "ATGGATGGGATCATGGTGACCTGGAAAGACAACTTTGACTCCTTCTACAGTGAAGTGGCT",
  "GAGCTTGGCAGGGGCAGATTCTCTGTCGTTAAGAAATGTGATCAGAAAGGAACCAAGCGA",
  "GCAGTGGCCACTAAGTTTGTGAACAAGAAGTTGATGAAGCGCGACCAGGTCACCCATGAG",
  "CTTGGCATCCTGCAGAGCCTCCAGCACCCCCTGCTTGTCGGCCTCCTCGACACCTTTGAG",
  "ACCCCCACCAGCTACATCCTGGTCTTAGAAATGGCTGACCAGGGTCGCCTCCTGGACTGC",
  "GTGGTGCGATGGGGAAGCCTCACTGAAGGGAAGATCAGGGCGCACCTGGGGGAGGTTCTG",
  "GAAGCTGTCCGGTACCTGCACAACTGCAGGATAGCACACCTGGACCTAAAGCCTGAGAAT",
  "ATCCTGGTGGATGAGAGTTTAGCCAAGCCAACCATCAAACTGGCTGACTTTGGAGATGCT",
  "GTTCAGCTCAACACGACCTACTACATCCACCAGTTACTGGGGAACCCTGAATTCGCAGCC",
  "CCTGAAATCATCCTCGGGAACCCTGTCTCCCTGACCTCGGATACGTGGAGTGTTGGAGTG",
  "CTCACATACGTACTTCTTAGTGGCGTGTCCCCCTTCCTGGATGACAGTGTGGAAGAGACC",
  "TGCCTGAACATTTGCCGCTTAGACTTTAGCTTCCCAGATGACTACTTTAAAGGAGTGAGC",
  "CAGAAGGCCAAGGAGTTCGTGTGCTTCCTCCTGCAGGAGGACCCCGCCAAGCGTCCCTCG",
  "GCTGCGCTGGCCCTCCAGGAGCAGTGGCTGCAGGCCGGCAACGGCAGAAGCACGGGCGTC",
  "CTCGACACGTCCAGACTGACTTCCTTCATTGAGCGGCGCAAACACCAGAATGATGTTCGA",
  "CCTATCCGTAGCATTAAAAACTTTCTGCAGAGCAGGCTTCTGCCTAGAGTTTGA"
)
