# Cross-language equivalence tests: R primitives vs OOGGA Python golden reference
#
# These tests verify that our R implementation of OOGGA's collision-checking
# primitives produces identical results to the original Python code.
#
# Golden reference: tests/testthat/fixtures/oogga_golden_reference.json
# Generated by: scripts/oogga_golden_reference.py
# Source: OOGGA.py (Mukundan & Madhusudhan 2025, github.com/bigbigdumdum/OOGGA)

# Load the golden reference JSON once for all tests
golden_path <- test_path("fixtures", "oogga_golden_reference.json")
golden <- NULL
if (file.exists(golden_path)) {
  golden <- jsonlite::fromJSON(golden_path, simplifyVector = FALSE)
}

# =============================================================================
# 1. Reverse complement equivalence
# =============================================================================

test_that("reverse_complement matches OOGGA Python get_rc()", {
  skip_if(is.null(golden), "Golden reference not found")

  for (tc in golden$tests$reverse_complement) {
    expect_equal(
      reverse_complement(tc$input), tc$rc,
      info = paste("RC of", tc$input)
    )
  }
})

# =============================================================================
# 2. Positional identity equivalence
# =============================================================================

test_that("count_positional_identity matches OOGGA Python find_identities()", {
  skip_if(is.null(golden), "Golden reference not found")

  for (tc in golden$tests$positional_identity) {
    expect_equal(
      count_positional_identity(tc$oh_a, tc$oh_b),
      as.integer(tc$identity),
      info = paste("identity(", tc$oh_a, ",", tc$oh_b, ")")
    )
  }
})

# =============================================================================
# 3. Self-palindrome check equivalence
# =============================================================================

test_that("oogga_overlap_pass self-palindrome matches OOGGA Python at mi=2", {
  skip_if(is.null(golden), "Golden reference not found")

  compat <- build_oh_compatibility(max_identity = 2L)

  for (tc in golden$tests$self_palindrome) {
    # overlap_pass with no prior/alien tests only self-palindrome
    r_result <- oogga_overlap_pass(
      tc$candidate, character(0), character(0),
      compat,
      max_identity = 2L
    )
    expect_equal(
      r_result, tc$passes_mi2,
      info = paste("self-palindrome", tc$candidate, "at mi=2")
    )
  }
})

test_that("oogga_overlap_pass self-palindrome matches OOGGA Python at mi=3", {
  skip_if(is.null(golden), "Golden reference not found")

  compat <- build_oh_compatibility(max_identity = 3L)

  for (tc in golden$tests$self_palindrome) {
    r_result <- oogga_overlap_pass(
      tc$candidate, character(0), character(0),
      compat,
      max_identity = 3L
    )
    expect_equal(
      r_result, tc$passes_mi3,
      info = paste("self-palindrome", tc$candidate, "at mi=3")
    )
  }
})

test_that("identity_with_rc values match OOGGA Python", {
  skip_if(is.null(golden), "Golden reference not found")

  for (tc in golden$tests$self_palindrome) {
    rc_cand <- reverse_complement(tc$candidate)
    r_id <- count_positional_identity(tc$candidate, rc_cand)
    expect_equal(
      r_id, as.integer(tc$identity_with_rc),
      info = paste(
        "identity(", tc$candidate, ", RC(", tc$candidate, ")) =",
        "identity(", tc$candidate, ",", tc$rc_candidate, ")"
      )
    )
  }
})

# =============================================================================
# 4. Pairwise compatibility equivalence
# =============================================================================

test_that("pairwise compat matches OOGGA Python 2-condition check", {
  skip_if(is.null(golden), "Golden reference not found")

  compat_mi2 <- build_oh_compatibility(max_identity = 2L)
  compat_mi3 <- build_oh_compatibility(max_identity = 3L)

  for (tc in golden$tests$pairwise_compatibility) {
    # Verify identity counts
    expect_equal(
      count_positional_identity(tc$candidate, tc$other),
      as.integer(tc$identity_direct),
      info = paste("direct identity:", tc$candidate, "vs", tc$other)
    )
    expect_equal(
      reverse_complement(tc$other), tc$rc_other,
      info = paste("RC(", tc$other, ")")
    )
    expect_equal(
      count_positional_identity(tc$candidate, tc$rc_other),
      as.integer(tc$identity_with_rc),
      info = paste("RC identity:", tc$candidate, "vs RC(", tc$other, ")")
    )

    # Verify full overlap_pass result at mi=2
    # Note: overlap_pass also checks self-palindrome of candidate.
    # If candidate is a palindrome, it will fail regardless of the other OH.
    # Python's overlap_pass includes RC(candidate) in the check list.
    r_mi2 <- oogga_overlap_pass(
      tc$candidate, c(tc$other), character(0),
      compat_mi2,
      max_identity = 2L
    )
    expect_equal(
      r_mi2, tc$passes_mi2,
      info = paste(
        "overlap_pass mi=2:", tc$candidate, "vs", tc$other,
        "(", tc$description, ")"
      )
    )

    # Verify at mi=3
    r_mi3 <- oogga_overlap_pass(
      tc$candidate, c(tc$other), character(0),
      compat_mi3,
      max_identity = 3L
    )
    expect_equal(
      r_mi3, tc$passes_mi3,
      info = paste(
        "overlap_pass mi=3:", tc$candidate, "vs", tc$other,
        "(", tc$description, ")"
      )
    )
  }
})

# =============================================================================
# 5. Full overlap_pass with prior + alien overhangs
# =============================================================================

test_that("full overlap_pass scenarios match OOGGA Python", {
  skip_if(is.null(golden), "Golden reference not found")

  compat_mi2 <- build_oh_compatibility(max_identity = 2L)
  compat_mi3 <- build_oh_compatibility(max_identity = 3L)

  for (tc in golden$tests$full_overlap_pass) {
    # Skip the Potapov set test (handled separately below)
    if (!is.null(tc$name) && tc$name == "potapov_set3_mutual_compat") next
    # Skip the mi2/mi3 comparison test (handled separately)
    if (!is.null(tc$name) && tc$name == "passes_mi3_fails_mi2") next

    mi <- if (!is.null(tc$max_identity)) as.integer(tc$max_identity) else 2L
    compat <- if (mi == 2L) compat_mi2 else compat_mi3

    prior <- if (!is.null(tc$prior_ohs)) unlist(tc$prior_ohs) else character(0)
    alien <- if (!is.null(tc$alien_ohs)) unlist(tc$alien_ohs) else character(0)

    r_result <- oogga_overlap_pass(
      tc$candidate, prior, alien, compat,
      max_identity = mi
    )
    expect_equal(
      r_result, tc$result,
      info = paste("full overlap_pass:", tc$name)
    )
  }
})

test_that("mi2 vs mi3 fallback matches OOGGA Python", {
  skip_if(is.null(golden), "Golden reference not found")

  compat_mi2 <- build_oh_compatibility(max_identity = 2L)
  compat_mi3 <- build_oh_compatibility(max_identity = 3L)

  # Find the passes_mi3_fails_mi2 scenario
  for (tc in golden$tests$full_overlap_pass) {
    if (is.null(tc$name) || tc$name != "passes_mi3_fails_mi2") next

    prior <- unlist(tc$prior_ohs)
    alien <- if (!is.null(tc$alien_ohs)) unlist(tc$alien_ohs) else character(0)

    r_mi2 <- oogga_overlap_pass(tc$candidate, prior, alien, compat_mi2, 2L)
    r_mi3 <- oogga_overlap_pass(tc$candidate, prior, alien, compat_mi3, 3L)

    expect_equal(r_mi2, tc$result_mi2, info = "mi=2 result")
    expect_equal(r_mi3, tc$result_mi3, info = "mi=3 result")
    # Confirm it fails at mi=2 but passes at mi=3
    expect_false(r_mi2, info = "should fail at mi=2")
    expect_true(r_mi3, info = "should pass at mi=3")
  }
})

test_that("Potapov Set 3 mutual compat matches OOGGA Python", {
  skip_if(is.null(golden), "Golden reference not found")

  compat_mi2 <- build_oh_compatibility(max_identity = 2L)

  # Find the Potapov set test
  for (tc in golden$tests$full_overlap_pass) {
    if (is.null(tc$name) || tc$name != "potapov_set3_mutual_compat") next

    potapov <- unlist(tc$potapov_set3)

    for (i in seq_along(potapov)) {
      oh <- potapov[i]
      others <- potapov[-i]

      r_result <- oogga_overlap_pass(oh, others, character(0), compat_mi2, 2L)
      py_result <- tc$all_pass_mi2[[oh]]

      expect_equal(
        r_result, py_result,
        info = paste("Potapov Set 3:", oh, "vs all others")
      )
    }

    # Verify aggregate counts
    n_passing_r <- sum(vapply(seq_along(potapov), function(i) {
      oogga_overlap_pass(potapov[i], potapov[-i], character(0), compat_mi2, 2L)
    }, logical(1)))

    expect_equal(n_passing_r, as.integer(tc$n_passing),
      info = "Potapov Set 3 total passing count"
    )
  }
})

# =============================================================================
# 6. build_oh_compatibility equivalence (2-condition check)
# =============================================================================
# Verify the compat matrix encodes exactly the 2-condition OOGGA check:
#   compat[A, B] = TRUE iff:
#     identity(A, B) <= max_identity AND
#     identity(A, RC(B)) <= max_identity

test_that("compat matrix encodes exactly OOGGA's 2-condition check", {
  compat <- build_oh_compatibility(max_identity = 2L)

  # Test a sample of pairs to verify both conditions
  test_pairs <- list(
    # (A, B, expected_compat, reason)
    list("AATC", "AATG", FALSE, "id(A,B)=3 > 2"),
    list("AATC", "CATT", FALSE, "id(A,B)=2, id(A,RC(CATT))=id(A,AATG)=3 > 2"),
    list("ACCA", "TGGT", FALSE, "id(A,B)=0, id(A,RC(TGGT))=id(A,ACCA)=4"),
    list("CCTC", "GAGG", FALSE, "id(A,RC(B))=id(A,CCTC)=4"),
    list("ACAA", "TAGA", TRUE, "low identity both ways")
  )

  for (tp in test_pairs) {
    oh_a <- tp[[1]]
    oh_b <- tp[[2]]
    expected <- tp[[3]]
    reason <- tp[[4]]

    # Manually verify the 2 conditions
    id_ab <- count_positional_identity(oh_a, oh_b)
    id_a_rcb <- count_positional_identity(oh_a, reverse_complement(oh_b))
    manual_result <- (id_ab <= 2L) && (id_a_rcb <= 2L)

    # Matrix should match manual computation
    expect_equal(compat[oh_a, oh_b], manual_result,
      info = paste("manual check:", oh_a, "vs", oh_b)
    )
    expect_equal(compat[oh_a, oh_b], expected,
      info = paste("expected:", oh_a, "vs", oh_b, "-", reason)
    )
  }
})

test_that("identity(A, RC(B)) == identity(RC(A), B) always (3rd condition is redundant)", {
  # Mathematical proof: identity(A, RC(B)) counts positions i where
  # A[i] == complement(B[3-i]). Substituting j=3-i, identity(RC(A), B) counts
  # positions j where A[j] == complement(B[3-j]) — the same set.
  # So the "extra" identity(RC(A), B) check removed from build_oh_compatibility()
  # was redundant (not wrong). The 2-condition and 3-condition matrices are identical.

  # Verify this equivalence on a sample of 1000 random pairs
  bases <- c("A", "C", "G", "T")
  all_ohs <- do.call(paste0, expand.grid(
    bases, bases, bases, bases,
    stringsAsFactors = FALSE
  ))
  set.seed(42)
  sample_pairs <- data.frame(
    a = sample(all_ohs, 1000, replace = TRUE),
    b = sample(all_ohs, 1000, replace = TRUE),
    stringsAsFactors = FALSE
  )

  for (i in seq_len(nrow(sample_pairs))) {
    a <- sample_pairs$a[i]
    b <- sample_pairs$b[i]
    id_a_rcb <- count_positional_identity(a, reverse_complement(b))
    id_rca_b <- count_positional_identity(reverse_complement(a), b)
    expect_equal(
      id_a_rcb, id_rca_b,
      info = paste("identity(", a, ", RC(", b, ")) == identity(RC(", a, "),", b, ")")
    )
  }
})
