#!/usr/bin/env bash
# Created: 2026-03-01
# Last updated: 2026-03-01 — Initial creation of timeline generator script

# update_timeline.sh — Generate TIMELINE.md from git history
#
# Groups commits by date, highlights PR merges, and preserves a manual
# milestones section fenced between MANUAL_MILESTONES markers.
#
# Usage: ./tools/update_timeline.sh

set -euo pipefail

# Resolve repo root (works whether called from repo root or tools/)
REPO_ROOT="$(git rev-parse --show-toplevel)"
TIMELINE_FILE="${REPO_ROOT}/TIMELINE.md"

# --- Preserve existing manual milestones section if present ---
MILESTONES_CONTENT=""
if [[ -f "${TIMELINE_FILE}" ]]; then
    # Extract everything between the milestone fences (inclusive of fences)
    MILESTONES_CONTENT=$(sed -n '/<!-- MANUAL_MILESTONES_START -->/,/<!-- MANUAL_MILESTONES_END -->/p' "${TIMELINE_FILE}" || true)
fi

# --- Gather git log data ---
TOTAL_COMMITS=$(git -C "${REPO_ROOT}" rev-list --count HEAD)
GENERATION_TIME=$(date '+%Y-%m-%d %H:%M:%S')
FIRST_COMMIT_DATE=$(git -C "${REPO_ROOT}" log --reverse --format="%ad" --date=short | head -1 || true)
LATEST_COMMIT_DATE=$(git -C "${REPO_ROOT}" log -1 --format="%ad" --date=short)

# Capture the full git log into a variable to avoid pipe/subshell issues
GIT_LOG=$(git -C "${REPO_ROOT}" log --date=short --format="%ad|%s")

# --- Build the timeline into a temp file, then move ---
TMPFILE=$(mktemp)
trap 'rm -f "${TMPFILE}"' EXIT

{
    # Header with file timestamps (markdown comment style)
    echo "<!-- Created: 2026-03-01 -->"
    echo "<!-- Last updated: $(date '+%Y-%m-%d') -- Auto-generated by tools/update_timeline.sh -->"
    echo ""
    echo "# Project Timeline"
    echo ""
    echo "> Auto-generated on ${GENERATION_TIME} | ${TOTAL_COMMITS} commits | ${FIRST_COMMIT_DATE} to ${LATEST_COMMIT_DATE}"
    echo ""

    # Manual milestones section — preserve existing or create empty fences
    if [[ -n "${MILESTONES_CONTENT}" ]]; then
        echo "${MILESTONES_CONTENT}"
    else
        echo "<!-- MANUAL_MILESTONES_START -->"
        echo "## Milestones"
        echo ""
        echo "| Date | Milestone |"
        echo "|------|-----------|"
        echo ""
        echo "<!-- MANUAL_MILESTONES_END -->"
    fi

    echo ""
    echo "---"
    echo ""
    echo "## Commit History"
    echo ""

    # Group commits by date, newest first
    # Using <<< here-string instead of pipe to keep the loop in the main shell
    CURRENT_DATE=""
    while IFS='|' read -r commit_date commit_msg; do
        # New date group
        if [[ "${commit_date}" != "${CURRENT_DATE}" ]]; then
            if [[ -n "${CURRENT_DATE}" ]]; then
                echo ""  # blank line between date groups
            fi
            echo "### ${commit_date}"
            echo ""
            CURRENT_DATE="${commit_date}"
        fi

        # Highlight PR merges with a bold prefix
        # Using bash pattern matching instead of grep to avoid SIGPIPE
        if [[ "${commit_msg}" == *"Merge pull request"* ]]; then
            echo "- **[PR MERGE]** ${commit_msg}"
        else
            echo "- ${commit_msg}"
        fi
    done <<< "${GIT_LOG}"
} > "${TMPFILE}"

# Atomic move to final location
mv "${TMPFILE}" "${TIMELINE_FILE}"
# Clear the trap since we moved the file successfully
trap - EXIT

echo "TIMELINE.md updated (${TOTAL_COMMITS} commits)"
